import Head from 'next/head'
import Blog from '../components/Home/Blog'
import Contact from '../components/Home/Contact'
import Features from '../components/Home/Features'
import Footer from '../components/Home/Footer'
import Hero from '../components/Home/Hero'
import Navbar from '../components/Home/Navbar'
import Pricing from '../components/Home/Pricing'
import Section from '../components/Home/Section'
import Testimonial from '../components/Home/Testimonial'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Section />
      <Features />
      <Testimonial />
      <Pricing />
      <Blog />
      <Contact />
      <Footer/>
    </div>
  )
}
